# Generated by Django 4.2.7 on 2023-12-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('los_hannah_username', models.CharField(max_length=50)),
                ('los_hannah_email', models.EmailField(default=0, max_length=254)),
            ],
        ),
    ]
